sudo: false
before_install:
  - gem --version
  - git config --global user.name "Travis CI"
  - git config --global user.email "user@example.com"

rvm:
  - '2.4'
  - '2.3'
  - '2.2'
  - '2.1'
  - '2.0'
